### ISSUE TITLE
wrong message!

### ISSUE THREAD

**Issue by zahramajd** [Tabrizian/free.sh#5]
when I tried the wrong password, the message was 'Successful Login', which confused me.

**Comment by Tabrizian** [comment]
I'll fix it. Thanks for reporting.

**Comment by 1995parham** [comment]
I correct this in a new version of free.sh, [here](https://github.com/AUT-CEIT/free.sh)

**Comment by Tabrizian** [comment]
We're moving this repo to [here](github.com/AUT-CEIT/free.sh). I'll close this for now.
